[workspace]
members = ["lib", "bin/disko", "bin/disko-install"]
resolver = "3"

[workspace.package]
edition = "2024"
description = "Declarative disk partitioning tool"
license = "MIT"
version = "2.0.0"

[profile.release]
lto = "fat"
incremental = true
strip = true