# General
edition              = "2024"
error_on_unformatted = true
max_width            = 100
unstable_features    = true

# Functions + Blocks
fn_params_layout           = "Vertical"
fn_single_line             = true
match_arm_blocks           = false
match_block_trailing_comma = true
trailing_comma             = "Never"

# Macros
format_macro_bodies   = true
format_macro_matchers = true

# Imports 
group_imports       = "StdExternalCrate"
imports_granularity = "Module"
imports_layout      = "Vertical"

# Comments + Docs
comment_width                = 60
doc_comment_code_block_width = 80
format_code_in_doc_comments  = true
normalize_comments           = true
wrap_comments                = true

# Structs + Enums
condense_wildcard_suffixes   = true
enum_discrim_align_threshold = 30
inline_attribute_width       = 0
merge_derives                = false
reorder_impl_items           = true
struct_field_align_threshold = 30
use_field_init_shorthand     = true
where_single_line            = true
