[formatter.nix]
command = "nixfmt"
includes = ["*.nix"]

[formatter.deadnix]
command = "deadnix"
includes = ["*.nix"]

[formatter.shellcheck]
command = "shellcheck"
includes = ["*.sh"]

[formatter.rust]
command = "rustfmt"
includes = ["*.rs"]

[formatter.taplo]
command = "taplo"
options = ["fmt"]
includes = ["*.toml"]
